### ISSUE TITLE
folder rename within TEI Stylesheets profiles

### ISSUE THREAD

**Issue by peterstadler** [TEIC/tei-converter#5]
the folder `profiles/default/relaxng/` with the TEI Stylesheets has been renamed to `profiles/default/rng` which breaks current transformations to RelaxNG. (see https://github.com/TEIC/Stylesheets/issues/543 for the motivation to change the name)

I do think we should support both names in the OxGarage, though, at least for some period of time. Otherwise several TEIGarage instances will fail for an unsupported combination of Stylesheets and TEIGarage.

**Comment by peterstadler** [comment]
@anneferger is this the right place to change the name? 
https://github.com/TEIC/tei-converter/blob/6ae4f048ef19c3bc217100461df24a3d68fc3a16/src/main/java/pl/psnc/dl/ege/tei/Format.java#L22

But how could we support both Stylesheets versions, i.e. the old ones with `profiles/default/relaxng/` and the new ones with `profiles/default/rng/`?

**Comment by anneferger** [comment]
Fixed in dbbb801612
